//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSToolbarPlugin\src\main\java\com\ashera\toolbar\SearchViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SearchViewImpl")
#ifdef RESTRICT_SearchViewImpl
#define INCLUDE_ALL_SearchViewImpl 0
#else
#define INCLUDE_ALL_SearchViewImpl 1
#endif
#undef RESTRICT_SearchViewImpl

#if !defined (ASSearchViewImpl_) && (INCLUDE_ALL_SearchViewImpl || defined(INCLUDE_ASSearchViewImpl))
#define ASSearchViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASSearchViewImpl_SearchViewBean;
@class ASSearchViewImpl_SearchViewCommandBuilder;
@class ASSearchViewImpl_SearchViewCommandParamsBuilder;
@class ASSearchViewImpl_SearchViewParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASSearchViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASSearchViewImpl_SearchViewBean *)getBean;

- (ASSearchViewImpl_SearchViewCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASSearchViewImpl_SearchViewParamsBean *)getParamsBean;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateViewWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSearchViewImpl)

inline NSString *ASSearchViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSearchViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSearchViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASSearchViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSearchViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSearchViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASSearchViewImpl_init(ASSearchViewImpl *self);

FOUNDATION_EXPORT ASSearchViewImpl *new_ASSearchViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl *create_ASSearchViewImpl_init(void);

FOUNDATION_EXPORT void ASSearchViewImpl_initWithNSString_(ASSearchViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASSearchViewImpl *new_ASSearchViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl *create_ASSearchViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASSearchViewImpl_initWithNSString_withNSString_(ASSearchViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASSearchViewImpl *new_ASSearchViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl *create_ASSearchViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASSearchViewImpl)

@compatibility_alias ComAsheraToolbarSearchViewImpl ASSearchViewImpl;

#endif

#if !defined (ASSearchViewImpl_SearchViewExt_) && (INCLUDE_ALL_SearchViewImpl || defined(INCLUDE_ASSearchViewImpl_SearchViewExt))
#define ASSearchViewImpl_SearchViewExt_

#define RESTRICT_SearchView 1
#define INCLUDE_ADXSearchView 1
#include "SearchView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASSearchViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASSearchViewImpl_SearchViewExt : ADXSearchView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASSearchViewImpl:(ASSearchViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSearchViewImpl_SearchViewExt)

FOUNDATION_EXPORT void ASSearchViewImpl_SearchViewExt_initWithASSearchViewImpl_(ASSearchViewImpl_SearchViewExt *self, ASSearchViewImpl *outer$);

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewExt *new_ASSearchViewImpl_SearchViewExt_initWithASSearchViewImpl_(ASSearchViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewExt *create_ASSearchViewImpl_SearchViewExt_initWithASSearchViewImpl_(ASSearchViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSearchViewImpl_SearchViewExt)

#endif

#if !defined (ASSearchViewImpl_SearchViewCommandBuilder_) && (INCLUDE_ALL_SearchViewImpl || defined(INCLUDE_ASSearchViewImpl_SearchViewCommandBuilder))
#define ASSearchViewImpl_SearchViewCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASSearchViewImpl;

@interface ASSearchViewImpl_SearchViewCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASSearchViewImpl:(ASSearchViewImpl *)outer$;

- (ASSearchViewImpl_SearchViewCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                              withId:(id)arg1;

- (ASSearchViewImpl_SearchViewCommandBuilder *)addModelWithId:(id)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)endAnimator;

- (ASSearchViewImpl_SearchViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASSearchViewImpl_SearchViewCommandBuilder *)invalidate;

- (ASSearchViewImpl_SearchViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)requestLayout;

- (ASSearchViewImpl_SearchViewCommandBuilder *)reset;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)value;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASSearchViewImpl_SearchViewCommandBuilder *)startAnimator;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetAddStatesFromChildren;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetAlpha;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetBackground;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetBackgroundTint;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetBottom;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetClickable;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetClipChildren;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetClipToPadding;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetContentDescription;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetDuplicateParentState;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetEnabled;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetFocusable;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetForeground;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetForegroundGravity;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetForegroundTint;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetForegroundTintMode;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetId;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosAlpha;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosIsFocused;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosIsHidden;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosIsOpaque;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosTag;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosTintColor;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetKeepScreenOn;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetLayoutDirection;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetLayoutMode;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetLeft;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetLongClickable;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetMaxHeight;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetMaxWidth;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetMinHeight;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetMinWidth;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetModelDescPath;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetModelIdPath;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetModelParam;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetModelPojoToUi;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetModelSyncEvents;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetModelUiToPojo;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetPaddingBottom;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetPaddingEnd;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetPaddingLeft;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetPaddingRight;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetPaddingStart;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetPaddingTop;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetRight;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetRotation;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetRotationX;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetRotationY;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetScaleX;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetScaleY;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetSelected;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetTextAlignment;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetTextDirection;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetTop;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetTransformPivotX;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetTransformPivotY;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetTranslationX;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetTranslationY;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetTranslationZ;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetValidateForm;

- (ASSearchViewImpl_SearchViewCommandBuilder *)tryGetVisibility;

- (ASSearchViewImpl_SearchViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                    withId:(id)arg1;

- (ASSearchViewImpl_SearchViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSearchViewImpl_SearchViewCommandBuilder)

FOUNDATION_EXPORT void ASSearchViewImpl_SearchViewCommandBuilder_initWithASSearchViewImpl_(ASSearchViewImpl_SearchViewCommandBuilder *self, ASSearchViewImpl *outer$);

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewCommandBuilder *new_ASSearchViewImpl_SearchViewCommandBuilder_initWithASSearchViewImpl_(ASSearchViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewCommandBuilder *create_ASSearchViewImpl_SearchViewCommandBuilder_initWithASSearchViewImpl_(ASSearchViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSearchViewImpl_SearchViewCommandBuilder)

#endif

#if !defined (ASSearchViewImpl_SearchViewBean_) && (INCLUDE_ALL_SearchViewImpl || defined(INCLUDE_ASSearchViewImpl_SearchViewBean))
#define ASSearchViewImpl_SearchViewBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASSearchViewImpl;
@protocol ASIWidget;

@interface ASSearchViewImpl_SearchViewBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASSearchViewImpl:(ASSearchViewImpl *)outer$;

- (void)setAttributeUnderTestWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSearchViewImpl_SearchViewBean)

FOUNDATION_EXPORT void ASSearchViewImpl_SearchViewBean_initWithASSearchViewImpl_(ASSearchViewImpl_SearchViewBean *self, ASSearchViewImpl *outer$);

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewBean *new_ASSearchViewImpl_SearchViewBean_initWithASSearchViewImpl_(ASSearchViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewBean *create_ASSearchViewImpl_SearchViewBean_initWithASSearchViewImpl_(ASSearchViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSearchViewImpl_SearchViewBean)

#endif

#if !defined (ASSearchViewImpl_SearchViewParamsBean_) && (INCLUDE_ALL_SearchViewImpl || defined(INCLUDE_ASSearchViewImpl_SearchViewParamsBean))
#define ASSearchViewImpl_SearchViewParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASSearchViewImpl;

@interface ASSearchViewImpl_SearchViewParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASSearchViewImpl:(ASSearchViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSearchViewImpl_SearchViewParamsBean)

FOUNDATION_EXPORT void ASSearchViewImpl_SearchViewParamsBean_initWithASSearchViewImpl_(ASSearchViewImpl_SearchViewParamsBean *self, ASSearchViewImpl *outer$);

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewParamsBean *new_ASSearchViewImpl_SearchViewParamsBean_initWithASSearchViewImpl_(ASSearchViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewParamsBean *create_ASSearchViewImpl_SearchViewParamsBean_initWithASSearchViewImpl_(ASSearchViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSearchViewImpl_SearchViewParamsBean)

#endif

#if !defined (ASSearchViewImpl_SearchViewCommandParamsBuilder_) && (INCLUDE_ALL_SearchViewImpl || defined(INCLUDE_ASSearchViewImpl_SearchViewCommandParamsBuilder))
#define ASSearchViewImpl_SearchViewCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASSearchViewImpl;

@interface ASSearchViewImpl_SearchViewCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASSearchViewImpl:(ASSearchViewImpl *)outer$;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)reset;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASSearchViewImpl_SearchViewCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSearchViewImpl_SearchViewCommandParamsBuilder)

FOUNDATION_EXPORT void ASSearchViewImpl_SearchViewCommandParamsBuilder_initWithASSearchViewImpl_(ASSearchViewImpl_SearchViewCommandParamsBuilder *self, ASSearchViewImpl *outer$);

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewCommandParamsBuilder *new_ASSearchViewImpl_SearchViewCommandParamsBuilder_initWithASSearchViewImpl_(ASSearchViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewCommandParamsBuilder *create_ASSearchViewImpl_SearchViewCommandParamsBuilder_initWithASSearchViewImpl_(ASSearchViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSearchViewImpl_SearchViewCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_SearchViewImpl")
