//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSToolbarPlugin\src\main\java\com\ashera\toolbar\SearchViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SearchViewImpl")
#ifdef RESTRICT_SearchViewImpl
#define INCLUDE_ALL_SearchViewImpl 0
#else
#define INCLUDE_ALL_SearchViewImpl 1
#endif
#undef RESTRICT_SearchViewImpl

#if !defined (ASSearchViewImpl_) && (INCLUDE_ALL_SearchViewImpl || defined(INCLUDE_ASSearchViewImpl))
#define ASSearchViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASSearchViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateViewWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSearchViewImpl)

inline NSString *ASSearchViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSearchViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSearchViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASSearchViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASSearchViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASSearchViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASSearchViewImpl_init(ASSearchViewImpl *self);

FOUNDATION_EXPORT ASSearchViewImpl *new_ASSearchViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl *create_ASSearchViewImpl_init(void);

FOUNDATION_EXPORT void ASSearchViewImpl_initWithNSString_(ASSearchViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASSearchViewImpl *new_ASSearchViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl *create_ASSearchViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASSearchViewImpl_initWithNSString_withNSString_(ASSearchViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASSearchViewImpl *new_ASSearchViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl *create_ASSearchViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASSearchViewImpl)

@compatibility_alias ComAsheraToolbarSearchViewImpl ASSearchViewImpl;

#endif

#if !defined (ASSearchViewImpl_SearchViewExt_) && (INCLUDE_ALL_SearchViewImpl || defined(INCLUDE_ASSearchViewImpl_SearchViewExt))
#define ASSearchViewImpl_SearchViewExt_

#define RESTRICT_SearchView 1
#define INCLUDE_ADXSearchView 1
#include "SearchView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASSearchViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASSearchViewImpl_SearchViewExt : ADXSearchView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASSearchViewImpl:(ASSearchViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASSearchViewImpl_SearchViewExt)

FOUNDATION_EXPORT void ASSearchViewImpl_SearchViewExt_initWithASSearchViewImpl_(ASSearchViewImpl_SearchViewExt *self, ASSearchViewImpl *outer$);

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewExt *new_ASSearchViewImpl_SearchViewExt_initWithASSearchViewImpl_(ASSearchViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASSearchViewImpl_SearchViewExt *create_ASSearchViewImpl_SearchViewExt_initWithASSearchViewImpl_(ASSearchViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASSearchViewImpl_SearchViewExt)

#endif

#pragma pop_macro("INCLUDE_ALL_SearchViewImpl")
