//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSToolbarPlugin\src\main\java\com\ashera\toolbar\ToolbarImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ToolbarImpl")
#ifdef RESTRICT_ToolbarImpl
#define INCLUDE_ALL_ToolbarImpl 0
#else
#define INCLUDE_ALL_ToolbarImpl 1
#endif
#undef RESTRICT_ToolbarImpl

#if !defined (ASToolbarImpl_) && (INCLUDE_ALL_ToolbarImpl || defined(INCLUDE_ASToolbarImpl))
#define ASToolbarImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ADXToolbar_OnMenuItemClickListener;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASToolbarImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (id<ADXToolbar_OnMenuItemClickListener>)getOnMenuItemClickListener;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASToolbarImpl)

inline NSString *ASToolbarImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASToolbarImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASToolbarImpl, LOCAL_NAME, NSString *)

inline NSString *ASToolbarImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASToolbarImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASToolbarImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASToolbarImpl_init(ASToolbarImpl *self);

FOUNDATION_EXPORT ASToolbarImpl *new_ASToolbarImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASToolbarImpl *create_ASToolbarImpl_init(void);

FOUNDATION_EXPORT void ASToolbarImpl_initWithNSString_(ASToolbarImpl *self, NSString *localname);

FOUNDATION_EXPORT ASToolbarImpl *new_ASToolbarImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASToolbarImpl *create_ASToolbarImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASToolbarImpl_initWithNSString_withNSString_(ASToolbarImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASToolbarImpl *new_ASToolbarImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASToolbarImpl *create_ASToolbarImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASToolbarImpl)

@compatibility_alias ComAsheraToolbarToolbarImpl ASToolbarImpl;


#endif

#if !defined (ASToolbarImpl_PreMeasureHandler_) && (INCLUDE_ALL_ToolbarImpl || defined(INCLUDE_ASToolbarImpl_PreMeasureHandler))
#define ASToolbarImpl_PreMeasureHandler_

#define RESTRICT_EventBusHandler 1
#define INCLUDE_ASEventBusHandler 1
#include "EventBusHandler.h"

@class ASToolbarImpl;
@class NSString;

@interface ASToolbarImpl_PreMeasureHandler : ASEventBusHandler

#pragma mark Public

- (instancetype)initWithASToolbarImpl:(ASToolbarImpl *)outer$
                         withNSString:(NSString *)type;

#pragma mark Protected

- (void)doPerformWithId:(id)payload;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASToolbarImpl_PreMeasureHandler)

FOUNDATION_EXPORT void ASToolbarImpl_PreMeasureHandler_initWithASToolbarImpl_withNSString_(ASToolbarImpl_PreMeasureHandler *self, ASToolbarImpl *outer$, NSString *type);

FOUNDATION_EXPORT ASToolbarImpl_PreMeasureHandler *new_ASToolbarImpl_PreMeasureHandler_initWithASToolbarImpl_withNSString_(ASToolbarImpl *outer$, NSString *type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASToolbarImpl_PreMeasureHandler *create_ASToolbarImpl_PreMeasureHandler_initWithASToolbarImpl_withNSString_(ASToolbarImpl *outer$, NSString *type);

J2OBJC_TYPE_LITERAL_HEADER(ASToolbarImpl_PreMeasureHandler)


#endif

#if !defined (ASToolbarImpl_ToolbarExt_) && (INCLUDE_ALL_ToolbarImpl || defined(INCLUDE_ASToolbarImpl_ToolbarExt))
#define ASToolbarImpl_ToolbarExt_

#define RESTRICT_Toolbar 1
#define INCLUDE_ADXToolbar 1
#include "Toolbar.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASToolbarImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASToolbarImpl_ToolbarExt : ADXToolbar < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASToolbarImpl:(ASToolbarImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASToolbarImpl_ToolbarExt)

FOUNDATION_EXPORT void ASToolbarImpl_ToolbarExt_initWithASToolbarImpl_(ASToolbarImpl_ToolbarExt *self, ASToolbarImpl *outer$);

FOUNDATION_EXPORT ASToolbarImpl_ToolbarExt *new_ASToolbarImpl_ToolbarExt_initWithASToolbarImpl_(ASToolbarImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASToolbarImpl_ToolbarExt *create_ASToolbarImpl_ToolbarExt_initWithASToolbarImpl_(ASToolbarImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASToolbarImpl_ToolbarExt)


#endif

#if !defined (ASToolbarImpl_ValueSetter_) && (INCLUDE_ALL_ToolbarImpl || defined(INCLUDE_ASToolbarImpl_ValueSetter))
#define ASToolbarImpl_ValueSetter_

@class ADXBadgeDrawable;

@protocol ASToolbarImpl_ValueSetter < JavaObject >

- (void)setValueOnBadgeDrawableWithADXBadgeDrawable:(ADXBadgeDrawable *)badgeDrawable
                                             withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ASToolbarImpl_ValueSetter)

J2OBJC_TYPE_LITERAL_HEADER(ASToolbarImpl_ValueSetter)


#endif

#pragma pop_macro("INCLUDE_ALL_ToolbarImpl")
